package github.timpcunningham.problems.problem_2;

import github.timpcunningham.Problem;
import github.timpcunningham.Report;

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
* */

public class Problem_2 implements Problem {
    @Override
    public void answer() {
        int first = 1, second = 2;
        int temp = 0;
        int result = 2; //account for second already being even (2)

        while(second < 4000000) {
            temp = first + second;

            if(temp % 2 == 0) {
                result += temp;
            }

            first = second;
            second = temp;
        }

        Report.reportNumber(2, result);
    }
}
